# 系统配置部分
system:
  domain: prod.mall        # 项目域名
  version: 1.0             # 项目版本
  env: "prod"              # 当前运行环境（生产环境）
  HttpPort: ":5001"        # HTTP 服务监听端口
  Host: "0.0.0.0"          # 生产环境通常监听所有接口
  UploadModel: "oss"       # 上传模式，例如阿里云OSS

# MySQL 数据库配置部分
mysql:
  default:
    dialect: "mysql"       # 数据库类型
    dbHost: "prod-db-host" # 生产数据库地址
    dbPort: "3306"         # 数据库端口
    dbName: "douyin_mall_prod"  # 数据库名称 (prod)
    userName: "prod_user"  # 生产数据库用户名
    password: "ProdPassword123!" # 生产数据库密码 (应通过环境变量或安全方式注入)
    charset: "utf8mb4"     # 数据库字符集

# Redis 配置部分（用于缓存和存储 JWT 令牌）
redis:
  redisHost: "prod-redis-host" # 生产Redis地址
  redisPort: "6379"          # Redis 服务器端口
  redisUsername: ""          # Redis 用户名（无则留空）
  redisPwd: "ProdRedisPassword" # 生产Redis密码 (应通过环境变量或安全方式注入)
  redisDbName: 0             # Redis 数据库编号
  redisNetwork: "tcp"        # 网络协议

# 缓存配置部分
cache:
  cacheType: redis         # 缓存类型（此处使用 Redis）
  cacheEmpires: 3600       # 缓存过期时间（单位：秒） (prod - 1 hour)
  cacheWarmUp: true        # 生产环境可能需要缓存预热
  cacheServer:             # 缓存服务器地址（可选）

# 加密密钥配置部分
encryptSecret:
  jwtSecret: "HighlySecureProductionJWTSecret!@#$"  # JWT 认证密钥 (prod - 应通过环境变量注入)
  emailSecret: "HighlySecureProductionEmailSecret"    # 邮件加密密钥 (prod)
  phoneSecret: "HighlySecureProductionPhoneSecret"    # 电话加密密钥 (prod)

# 邮件配置部分
email:
  validEmail: "noreply@prod.mall" # 有效邮箱
  smtpHost: "http://smtp.prod.example.com" # SMTP 主机地址
  smtpEmail: "noreply@prod.mall"     # SMTP 发送邮箱
  smtpPass: "ProdSmtpPassword"           # SMTP 邮箱密码 (应通过环境变量注入)
